


message_text_en = {
    1: "Blessed is the man who does not walk in the counsel of the wicked, nor stand in the path of sinners, nor sit in the seat of scoffers.",
    2: "Why do the nations rage, and the peoples plot in vain?",
    3: "O Lord, how many are my foes! Many are rising against me.",
    4: "Answer me when I call, O God of my righteousness! You have given me relief when I was in distress. Be gracious to me and hear my prayer.",
    5: "Give ear to my words, O Lord; consider my groaning.",
    6: "O Lord, rebuke me not in your anger, nor discipline me in your wrath.",
    7: "O Lord my God, in you I take refuge; save me from all my pursuers and deliver me,",
    8: "O Lord, our Lord, how majestic is your name in all the earth! You have set your glory above the heavens.",
    9: "I will give thanks to you, O Lord, with my whole heart; I will recount all of your wonderful deeds.",
    10: "Why, O Lord, do you stand far away? Why do you hide yourself in times of trouble?",
    11: "In the Lord I take refuge; how can you say to my soul, 'Flee like a bird to your mountain'?",
    12: "Save, O Lord, for the godly one is gone; for the faithful have vanished from among the children of man.",
    13: "How long, O Lord? Will you forget me forever? How long will you hide your face from me?",
    14: "The fool says in his heart, 'There is no God.' They are corrupt, doing abominable iniquity; there is none who does good.",
    15: "O Lord, who shall sojourn in your tent? Who shall dwell on your holy hill?",
    16: "Preserve me, O God, for in you I take refuge.",
    17: "O Lord, hear my righteousness; attend to my cry! Give ear to my prayer from lips free of deceit.",
    18: "I will love you, O Lord, my strength.",
    19: "The heavens declare the glory of God, and the sky above proclaims his handiwork.",
    20: "May the Lord answer you in the day of trouble! May the name of the God of Jacob protect you!",
    21: "The king rejoices in your strength, O Lord, and in your salvation how greatly he exults!",
    22: "My God, my God, why have you forsaken me? Why are you so far from saving me, from the words of my groaning?",
    23: "The Lord is my shepherd; I shall not want.",
    24: "The earth is the Lord's and the fullness thereof, the world and those who dwell therein.",
    25: "To you, O Lord, I lift up my soul.",
    26: "Judge me, O Lord, for I have walked in my integrity, and I have trusted in the Lord without wavering.",
    27: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?",
    28: "To you, O Lord, I call; my rock, be not deaf to me, lest, if you be silent to me, I become like those who go down to the pit.",
    29: "Ascribe to the Lord, O heavenly beings, ascribe to the Lord glory and strength.",
    30: "I will extol you, O Lord, for you have drawn me up and have not let my foes rejoice over me.",
    31: "In you, O Lord, do I take.",
    31: "In you, O LORD, I trust; never let me be put to shame. Deliver me in your righteousness.",
    32: "Blessed is the one whose transgression is forgiven, whose sin is covered.",
    33: "Rejoice in the LORD, you righteous ones; praise befits the upright.",
    34: "I will bless the LORD at all times; his praise shall continually be in my mouth.",
    35: "Contend, O LORD, with those who contend with me; fight against those who fight against me.",
    36: "The wicked man's transgression speaks to him within his heart; there is no fear of God before his eyes.",
    37: "Do not fret because of evildoers or be envious of those who do wrong.",
    38: "O LORD, do not rebuke me in your anger or discipline me in your wrath.",
    39: "I said, 'I will guard my ways that I may not sin with my tongue; I will keep a muzzle on my mouth as long as the wicked are in my presence.'",
    40: "I waited patiently for the LORD; he inclined to me and heard my cry.",
    41: "Blessed is the one who has regard for the weak; in the day of trouble, the LORD delivers him.",
    42: "As the deer pants for streams of water, so my soul longs after you, O God.",
    43: "Vindicate me, O God, and plead my cause against an ungodly nation; deliver me from deceitful and unjust men.",
    44: "We have heard with our ears, O God; our fathers have told us what you did in their days, in days of old.",
    45: "My heart is stirred by a noble theme as I recite my verses for the king; my tongue is the pen of a skillful writer.",
    46: "God is our refuge and strength, an ever-present help in trouble.",
    47: "Clap your hands, all you peoples; shout to God with a voice of joy.",
    48: "Great is the LORD, and greatly to be praised, in the city of our God, His holy mountain.",
    49: "Hear this, all you peoples; listen, all inhabitants of the world,",
    50: "The Mighty One, God, the LORD, speaks and summons the earth from the rising of the sun to its setting.",
    51: "Have mercy on me, O God, according to your steadfast love; blot out my transgressions according to your abundant mercy.",
    52: "Why do you boast of evil, O mighty man? The steadfast love of God endures all day long.",
    53: "The fool says in his heart, 'There is no God.' They are corrupt, and their ways are vile; there is no one who does good.",
    54: "Save me, O God, by your name; vindicate me by your might.",
    55: "Incline your ear to my prayer, O God, and hide not yourself from my plea for mercy!",
    56: "Be gracious to me, O God, for man tramples on me; all day long an attacker oppresses me.",
    57: "Be merciful to me, O God, be merciful to me, for in you my soul takes refuge; in the shadow of your wings I will take shelter, till the storms of destruction pass by.",
    58: "Do you indeed decree what is right, you gods? Do you judge the children of man uprightly?",
    59: "Deliver me, O my God, from my enemies; protect me from those who rise up against me.",
    60: "O God, you have rejected us; you have broken us; you have been angry; oh, restore",
    61: "Hear, O God, my cry; attend to my prayer.",
    62: "My soul waits in silence for God alone; from Him comes my salvation.",
    63: "O God, You are my God; earnestly I seek You; my soul thirsts for You; my flesh faints for You, as in a dry and weary land where there is no water.",
    64: "Hear, O God, my voice in my prayer; preserve my life from fear of the enemy.",
    65: "To You, O God, belongs the praise in Zion; to You shall vows be performed.",
    66: "Shout for joy to God, all the earth.",
    67: "May God be gracious to us and bless us; may His face shine upon us (Selah).",
    68: "Arise, O God, and scatter your enemies; let those who hate You flee before You.",
    69: "Deliver me, O God, for the waters have come up to my neck.",
    691: "Deliver me, O God, for the waters have come up to my neck.",
    70: "Make haste, O God, to deliver me; O LORD, make haste to help me.",
    71: "In You, O LORD, I put my trust; let me never be put to shame.",
    72: "O God, give the king Your justice, and Your righteousness to the royal son.",
    73: "Truly God is good to Israel, to those who are pure in heart.",
    74: "O God, why have You rejected us forever? Why does Your anger smoke against the sheep of Your pasture?",
    75: "To You, O God, we give thanks; to You we give thanks, for Your name is near. Your wondrous deeds declare it.",
    76: "God is known in Judah; His name is great in Israel.",
    77: "I cry aloud to God, aloud to God, and He will hear me.",
    78: "Hear my teaching, O my people; incline your ears to the words of my mouth.",
    79: "O God, the nations have come into Your inheritance; they have defiled Your holy temple; they have laid Jerusalem in ruins.",
    80: "Give ear, O Shepherd of Israel, You who lead Joseph like a flock! You who are enthroned upon the cherubim, shine forth.",
    81: "Sing aloud to God our strength; shout for joy to the God of Jacob.",
    82: "God has taken His place in the divine council; in the midst of the gods, He holds judgment.",
    83: "O God, do not keep silence; do not hold Your peace or be still, O God!",
    84: "How lovely is Your dwelling place, O LORD of hosts!",
    85: "You have blessed, O LORD, Your land; You have restored the fortunes of Jacob.",
    86: "Incline Your ear, O LORD, and answer me, for I am poor and needy.",
    87: "His foundation is on the holy mountains.",
    88: "O LORD, God of my salvation, I cry out day and night before You.",
    89: "I will sing of the steadfast love of the LORD forever; with my mouth I will make known Your faithfulness to all generations.",
    90: "LORD, You have been our dwelling place in all generations.",
    91: "He who dwells in the shelter of the Most High will abide in the shadow of the Almighty.",
    92: "It is good to give thanks to the LORD, to sing praises to Your name, O Most High;",
    93: "The LORD reigns; He is clothed with majesty. The LORD has clothed Himself with strength; He has girded Himself. The world also is established, so that it cannot be moved.",
    94: "O Lord God, to whom vengeance belongs—O God, to whom vengeance belongs, shine forth!",
    95: "Oh come, let us sing to the LORD! Let us shout joyfully to the Rock of our salvation.",
    96: "Sing to the LORD a new song; sing to the LORD, all the earth.",
    97: "The LORD reigns; let the earth rejoice; let the multitude of isles be glad!",
    98: "Sing to the LORD a new song, for He has done marvelous things; His right hand and His holy arm have gained Him the victory.",
    99: "The LORD reigns; let the peoples tremble! He dwells between the cherubim; let the earth be moved!",
    100: "Make a joyful shout to the LORD, all you lands!",
    101: "I will sing of mercy and justice; to You, O LORD, I will sing praises.",
    103: "Bless the LORD, O my soul; and all that is within me, bless His holy name!",
    104: "Bless the LORD, O my soul! O LORD my God, You are very great: You are clothed with honor and majesty.",
    105: "Oh, give thanks to the LORD! Call upon His name; make known His deeds among the peoples!",
    106: "Praise the LORD! Oh, give thanks to the LORD, for He is good! For His mercy endures forever.",
    107: "Oh, give thanks to the LORD, for He is good! For His mercy endures forever.",
    108: "My heart is steadfast, O God; I will sing and give praise, even with my glory.",
    109: "Do not keep silent, O God of my praise!",
    110: "The LORD said to my Lord, 'Sit at My right hand, till I make Your enemies Your footstool.'",
    111: "Praise the LORD! I will praise the LORD with my whole heart, in the assembly of the upright and in the congregation.",
    112: "Praise the LORD! Blessed is the man who fears the LORD, who delights greatly in His commandments.",
    113: "Praise the LORD! Praise, O servants of the LORD, praise the name of the LORD!",
    114: "When Israel went out of Egypt, the house of Jacob from a people of strange language,",
    115: "Not unto us, O LORD, not unto us, but to Your name give glory, because of Your mercy, because of Your truth.",
    116: "I love the LORD, because He has heard my voice and my supplications.",
    117: "Praise the LORD, all you Gentiles! Laud Him, all you peoples!",
    118: "Oh, give thanks to the LORD, for He is good! For His mercy endures forever.",
    119: "Blessed are the undefiled in the way, who walk in the law of the LORD!",
    120: "In my distress I cried to the LORD, and He heard me.",
    121: "I will lift up my eyes to the hills—From whence comes my help?",
    122: "I was glad when they said to me, 'Let us go into the house of the LORD.'",
    123: "Unto You I lift up my eyes, O You who dwell in the heavens.",
    124: "If it had not been the LORD who was on our side—Let Israel now say—",
    125: "Those who trust in the LORD are like Mount Zion, which cannot be moved, but abides",
    126: "When the LORD brought back the captivity of Zion, we were like those who dream.",
    127: "Unless the LORD builds the house, they labor in vain who build it; unless the LORD guards the city, the watchman stays awake in vain.",
    128: "Blessed is everyone who fears the LORD, who walks in His ways.",
    129: "Many times they have afflicted me from my youth; yet they have not prevailed against me.",
    130: "Out of the depths I have cried to You, O LORD.",
    131: "LORD, my heart is not haughty, nor my eyes lofty. Neither do I concern myself with great matters, nor with things too profound for me.",
    132: "Remember, LORD, the reproach of Your servant David, how I bear in my bosom the reproach of all the many peoples.",
    133: "Behold, how good and how pleasant it is for brethren to dwell together in unity!",
    134: "Behold, bless the LORD, all you servants of the LORD, who by night stand in the house of the LORD!",
    135: "Praise the LORD! Praise the name of the LORD; praise Him, O you servants of the LORD!",
    136: "Praise the LORD, for He is good; for His mercy endures forever.",
    137: "By the rivers of Babylon, there we sat down, yea, we wept when we remembered Zion.",
    138: "I will praise You with my whole heart; before the gods I will sing praises to You.",
    139: "O LORD, You have searched me and known me.",
    140: "Deliver me, O LORD, from evil men; preserve me from violent men,",
    141: "LORD, I cry out to You; make haste to me! Give ear to my voice when I cry out to You.",
    142: "With my voice I cry out to the LORD; with my voice I plead for mercy to the LORD.",
    143: "Hear my prayer, O LORD; give ear to my supplications! In Your faithfulness and righteousness, answer me.",
    144: "Blessed be the LORD my Rock, who trains my hands for war, and my fingers for battle.",
    145: "I will extol You, my God, O King; and I will bless Your name forever and ever.",
    146: "Praise the LORD! O my soul, praise the LORD!",
    147: "Praise the LORD, for it is good to sing praises to our God; for it is pleasant, and praise is beautiful.",
    148: "Praise the LORD! Praise the LORD from the heavens; praise Him in the heights!",
    149: "Praise the LORD! Sing to the LORD a new song, and His praise in the assembly of saints.",
    150: "Praise the LORD! Praise God in His sanctuary; praise Him in His mighty firmament.",
}
