


message_text_en = {
    1: "Blessed is the man who does not walk in the counsel of the wicked, nor stand in the path of sinners, nor sit in the seat of scoffers.",
    2: "Why do the nations rage, and the peoples plot in vain?",
    3: "O Lord, how many are my foes! Many are rising against me.",
    4: "Answer me when I call, O God of my righteousness! You have given me relief when I was in distress. Be gracious to me and hear my prayer.",
    5: "Give ear to my words, O Lord; consider my groaning.",
    6: "O Lord, rebuke me not in your anger, nor discipline me in your wrath.",
    7: "O Lord my God, in you I take refuge; save me from all my pursuers and deliver me,",
    8: "O Lord, our Lord, how majestic is your name in all the earth! You have set your glory above the heavens.",
    9: "I will give thanks to you, O Lord, with my whole heart; I will recount all of your wonderful deeds.",
    10: "Why, O Lord, do you stand far away? Why do you hide yourself in times of trouble?",
    11: "In the Lord I take refuge; how can you say to my soul, 'Flee like a bird to your mountain'?",
    12: "Save, O Lord, for the godly one is gone; for the faithful have vanished from among the children of man.",
    13: "How long, O Lord? Will you forget me forever? How long will you hide your face from me?",
    14: "The fool says in his heart, 'There is no God.' They are corrupt, doing abominable iniquity; there is none who does good.",
    15: "O Lord, who shall sojourn in your tent? Who shall dwell on your holy hill?",
    16: "Preserve me, O God, for in you I take refuge.",
    17: "O Lord, hear my righteousness; attend to my cry! Give ear to my prayer from lips free of deceit.",
    18: "I will love you, O Lord, my strength.",
    19: "The heavens declare the glory of God, and the sky above proclaims his handiwork.",
    20: "May the Lord answer you in the day of trouble! May the name of the God of Jacob protect you!",
    21: "The king rejoices in your strength, O Lord, and in your salvation how greatly he exults!",
    22: "My God, my God, why have you forsaken me? Why are you so far from saving me, from the words of my groaning?",
    23: "The Lord is my shepherd; I shall not want.",
    24: "The earth is the Lord's and the fullness thereof, the world and those who dwell therein.",
    25: "To you, O Lord, I lift up my soul.",
    26: "Judge me, O Lord, for I have walked in my integrity, and I have trusted in the Lord without wavering.",
    27: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?",
    28: "To you, O Lord, I call; my rock, be not deaf to me, lest, if you be silent to me, I become like those who go down to the pit.",
    29: "Ascribe to the Lord, O heavenly beings, ascribe to the Lord glory and strength.",
    30: "I will extol you, O Lord, for you have drawn me up and have not let my foes rejoice over me.",
    31: "In you, O Lord, do I take.",
    31: "In you, O LORD, I trust; never let me be put to shame. Deliver me in your righteousness.",
    32: "Blessed is the one whose transgression is forgiven, whose sin is covered.",
    33: "Rejoice in the LORD, you righteous ones; praise befits the upright.",
    34: "I will bless the LORD at all times; his praise shall continually be in my mouth.",
    35: "Contend, O LORD, with those who contend with me; fight against those who fight against me.",
    36: "The wicked man's transgression speaks to him within his heart; there is no fear of God before his eyes.",
    37: "Do not fret because of evildoers or be envious of those who do wrong.",
    38: "O LORD, do not rebuke me in your anger or discipline me in your wrath.",
    39: "I said, 'I will guard my ways that I may not sin with my tongue; I will keep a muzzle on my mouth as long as the wicked are in my presence.'",
    40: "I waited patiently for the LORD; he inclined to me and heard my cry.",
    41: "Blessed is the one who has regard for the weak; in the day of trouble, the LORD delivers him.",
    42: "As the deer pants for streams of water, so my soul longs after you, O God.",
    43: "Vindicate me, O God, and plead my cause against an ungodly nation; deliver me from deceitful and unjust men.",
    44: "We have heard with our ears, O God; our fathers have told us what you did in their days, in days of old.",
    45: "My heart is stirred by a noble theme as I recite my verses for the king; my tongue is the pen of a skillful writer.",
    46: "God is our refuge and strength, an ever-present help in trouble.",
    47: "Clap your hands, all you peoples; shout to God with a voice of joy.",
    48: "Great is the LORD, and greatly to be praised, in the city of our God, His holy mountain.",
    49: "Hear this, all you peoples; listen, all inhabitants of the world,",
    50: "The Mighty One, God, the LORD, speaks and summons the earth from the rising of the sun to its setting.",
    51: "Have mercy on me, O God, according to your steadfast love; blot out my transgressions according to your abundant mercy.",
    52: "Why do you boast of evil, O mighty man? The steadfast love of God endures all day long.",
    53: "The fool says in his heart, 'There is no God.' They are corrupt, and their ways are vile; there is no one who does good.",
    54: "Save me, O God, by your name; vindicate me by your might.",
    55: "Incline your ear to my prayer, O God, and hide not yourself from my plea for mercy!",
    56: "Be gracious to me, O God, for man tramples on me; all day long an attacker oppresses me.",
    57: "Be merciful to me, O God, be merciful to me, for in you my soul takes refuge; in the shadow of your wings I will take shelter, till the storms of destruction pass by.",
    58: "Do you indeed decree what is right, you gods? Do you judge the children of man uprightly?",
    59: "Deliver me, O my God, from my enemies; protect me from those who rise up against me.",
    60: "O God, you have rejected us; you have broken us; you have been angry; oh, restore",
    61: "Hear, O God, my cry; attend to my prayer.",
    62: "My soul waits in silence for God alone; from Him comes my salvation.",
    63: "O God, You are my God; earnestly I seek You; my soul thirsts for You; my flesh faints for You, as in a dry and weary land where there is no water.",
    64: "Hear, O God, my voice in my prayer; preserve my life from fear of the enemy.",
    65: "To You, O God, belongs the praise in Zion; to You shall vows be performed.",
    66: "Shout for joy to God, all the earth.",
    67: "May God be gracious to us and bless us; may His face shine upon us (Selah).",
    68: "Arise, O God, and scatter your enemies; let those who hate You flee before You.",
    69: "Deliver me, O God, for the waters have come up to my neck.",
    691: "Deliver me, O God, for the waters have come up to my neck.",
    70: "Make haste, O God, to deliver me; O LORD, make haste to help me.",
    71: "In You, O LORD, I put my trust; let me never be put to shame.",
    72: "O God, give the king Your justice, and Your righteousness to the royal son.",
    73: "Truly God is good to Israel, to those who are pure in heart.",
    74: "O God, why have You rejected us forever? Why does Your anger smoke against the sheep of Your pasture?",
    75: "To You, O God, we give thanks; to You we give thanks, for Your name is near. Your wondrous deeds declare it.",
    76: "God is known in Judah; His name is great in Israel.",
    77: "I cry aloud to God, aloud to God, and He will hear me.",
    78: "Hear my teaching, O my people; incline your ears to the words of my mouth.",
    79: "O God, the nations have come into Your inheritance; they have defiled Your holy temple; they have laid Jerusalem in ruins.",
    80: "Give ear, O Shepherd of Israel, You who lead Joseph like a flock! You who are enthroned upon the cherubim, shine forth.",
    81: "Sing aloud to God our strength; shout for joy to the God of Jacob.",
    82: "God has taken His place in the divine council; in the midst of the gods, He holds judgment.",
    83: "O God, do not keep silence; do not hold Your peace or be still, O God!",
    84: "How lovely is Your dwelling place, O LORD of hosts!",
    85: "You have blessed, O LORD, Your land; You have restored the fortunes of Jacob.",
    86: "Incline Your ear, O LORD, and answer me, for I am poor and needy.",
    87: "His foundation is on the holy mountains.",
    88: "O LORD, God of my salvation, I cry out day and night before You.",
    89: "I will sing of the steadfast love of the LORD forever; with my mouth I will make known Your faithfulness to all generations.",
    90: "LORD, You have been our dwelling place in all generations.",
    91: "He who dwells in the shelter of the Most High will abide in the shadow of the Almighty.",
    92: "It is good to give thanks to the LORD, to sing praises to Your name, O Most High;",
    93: "The LORD reigns; He is robed in majesty; the LORD is robed; He has put on strength as His belt. Yes",
}
