

message_text_pt = {
    1: "Bem-aventurado o homem que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores",
    2: "Por que se amotinam os gentios, e os povos imaginam coisas vàs?",
    3: "Senhor, como se têm multiplicado os meus adversários! São muitos os que se levantam contra mim.",
    4: "Ouve-me quando eu clamo, ó Deus da minha justiça, na angústia me deste largueza; tem misericórdia de mim e ouve a minha oração.",
    5: "DÁ ouvidos às minhas palavras, ó Senhor, atende à minha meditação.",
    6: "Senhor, não me repreendas na tua ira, nem me castigues no teu furor.",
    7: "Senhor meu Deus, em ti confio; salva-me de todos os que me perseguem, e livra-me;",
    8: "Ó Senhor, Senhor nosso, quão admirável é o teu nome em toda a terra, pois puseste a tua glória sobre os céus!",
    9: "Eu te louvarei, Senhor, com todo o meu coração; contarei todas as tuas maravilhas.",
    10: "Por que estás ao longe, SENHOR? Por que te escondes nos tempos de angústia?",
    11: "No SENHOR confio; como dizeis à minha alma: Fugi para a vossa montanha como pássaro?",
    12: "Salva-nos, SENHOR, porque faltam os homens bons; porque são poucos os fiéis entre os filhos dos homens.",
    13: "Até quando te esquecerás de mim, SENHOR? Para sempre? Até quando esconderás de mim o teu rosto?",
    14: "Disse o néscio no seu coração: Não há Deus. Têm-se corrompido, fazem-se abomináveis em suas obras, não há ninguém que faça o bem.",
    15: "SENHOR, quem habitará no teu tabernáculo? Quem morará no teu santo monte?",
    16: "Guarda-me, ó Deus, porque em ti confio.",
    17: "Ouve, SENHOR, a justiça; atende ao meu clamor; dá ouvidos à minha oração, que não é feita com lábios enganosos.",
    18: "Eu te amarei, ó SENHOR, fortaleza minha.",
    19: "Os céus declaram a glória de Deus e o firmamento anuncia a obra das suas mãos.",
    20: "O SENHOR te ouça no dia da angústia, o nome do Deus de Jacó te proteja.",
    21: "O rei se alegra em tua força, SENHOR; e na tua salvação grandemente se regozija.",
    22: "Deus meu, Deus meu, por que me desamparaste? Por que te alongas do meu auxílio e das palavras do meu bramido?",
    23: "O SENHOR é o meu pastor, nada me faltará.",
    24: "Do SENHOR é a terra e a sua plenitude, o mundo e aqueles que nele habitam.",
    25: "A ti, SENHOR, levanto a minha alma.",
    26: "Julga-me, SENHOR, pois tenho andado em minha sinceridade; tenho confiado também no SENHOR; não vacilarei.",
    27: "O SENHOR é a minha luz e a minha salvação; a quem temerei? O SENHOR é a força da minha vida; de quem me recearei?",
    28: "A ti clamarei, ó Senhor, Rocha minha; não emudeças para comigo; não aconteça, cal ando-te tu para comigo, que eu fique semelhante aos que descem ao abismo.",
    29: "Dai ao SENHOR, ó filhos dos poderosos, dai ao SENHOR glória e força.",
    30: "Exaltar-te-ei, ó SENHOR, porque tu me exaltaste; e não fizeste com que meus inimigos se alegrassem sobre mim.",
    31: "Em ti, SENHOR, confio; nunca me deixes confundido. Livra-me pela tua justiça.",
    32: "Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto.",
    33: "Regozijai-vos no SENHOR, vós justos, pois aos retos convém o louvor.",
    34: "Louvarei ao SENHOR em todo o tempo; o seu louvor estará continuamente na minha boca.",
    35: "Pleiteia, SENHOR, com aqueles que pleiteiam comigo; peleja contra os que pelejam contra mim.",
    36: "A transgressão do ímpio diz no íntimo do meu coração: Não há temor de Deus perante os seus olhos.",
    37: "NÃO te indignes por causa dos malfeitores, nem tenhas inveja dos que praticam a iniqüidade.",
    38: "Ó Senhor, não me repreendas na tua ira, nem me castigues no teu furor.",
    39: "Eu disse: Guardarei os meus caminhos para não pecar com a minha língua; guardarei a boca com um freio, enquanto o ímpio estiver diante de mim.",
    40: "Esperei com paciência no SENHOR, e ele se inclinou para mim, e ouviu o meu clamor.",
    41: "Bem-aventurado é aquele que atende ao pobre; o SENHOR o livrará no dia do mal.",
    42: "Assim como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus!",
    43: "Faze-me justiça, ó Deus, e pleiteia a minha causa contra a nação ímpia. Livra-me do homem fraudulento e injusto.",
    44: "Ó Deus, nós ouvimos com os nossos ouvidos, e nossos pais nos têm contado a obra que fizeste em seus dias, nos tempos da antiguidade.",
    45: "O meu coração ferve com palavras boas, falo do que tenho feito no tocante ao Rei. A minha língua é a pena de um destro escritor.",
    46: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.",
    47: "Batei palmas, todos os povos; aclamai a Deus com voz de triunfo.",
    48: "Grande é o SENHOR e mui digno de louvor, na cidade do nosso Deus, no seu monte santo.",
    49: "Ouvi isto, vós todos os povos; inclinai os ouvidos, todos os moradores do mundo,",
    50: "O Deus poderoso, o SENHOR, falou e chamou a terra desde o nascimento do sol até ao seu ocaso.",
    51: "Tem misericórdia de mim, ó Deus, segundo a tua benignidade; apaga as minhas transgressões, segundo a multidão das tuas misericórdias.",
    52: "Por que te glorias na malícia, ó homem poderoso? Pois a bondade de Deus permanece continuamente.",
    53: "Disse o néscio no seu coração: Não há Deus. Têm-se corrompido, e cometido abominável iniqüidade; não há ninguém que faça o bem.",
    54: "Salva-me, ó Deus, pelo teu nome, e faze-me justiça pelo teu poder.",
    55: "Inclina, ó Deus, os teus ouvidos à minha oração, e não te escondas da minha súplica.",
    56: "Tem misericórdia de mim, ó Deus, porque o homem procura devorar-me; pelejando todo dia, me oprime.",
    57: "Tem misericórdia de mim, ó Deus, tem misericórdia de mim, porque a minha alma confia em ti; e à sombra das tuas asas me abrigo, até que passem as calamidades.",
    58: "Acaso falais vós, deveras, ó congregação, a justiça? Julgais retamente, ó filhos dos homens?",
    59: "Livra-me, meu Deus, dos meus inimigos, defende-me daqueles que se levantam contra mim.",
    60: "Ó Deus, tu nos rejeitaste, tu nos espalhaste, tu te indignaste; oh, volta-te para nós.",
    61: "Ouve, ó Deus, o meu clamor; atende à minha oração.",
    62: "A minha alma espera somente em Deus; dele vem a minha salvação.",
    63: "Ó Deus, tu és o meu Deus, de madrugada te buscarei; a minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água;",
    64: "Ouve, ó Deus, a minha voz na minha oração; guarda a minha vida do temor do inimigo.",
    65: "A ti, ó Deus, espera o louvor em Sião, e a ti se pagará o voto.",
    66: "Celebrai com júbilo a Deus, todas as terras.",
    67: "Deus tenha misericórdia de nós e nos abençoe; e faça resplandecer o seu rosto sobre nós (Selá.)",
    68: "Levante-se Deus, e sejam dissipados os seus inimigos; fugirão de diante dele os que o odeiam.",
    69: "Livra-me, ó Deus, pois as águas entraram até à minha alma.",
    691: "Livra-me, ó Deus, pois as águas entraram até à minha alma.",
    70: "Apressa-te, ó Deus, em me livrar; SENHOR, apressa-te em ajudar-me.",
    71: "Em ti, SENHOR, confio; nunca seja eu confundido.",
    72: "Ó Deus, dá ao rei os teus juízos, e a tua justiça ao filho do rei.",
    73: "Verdadeiramente bom é Deus para com Israel, para com os limpos de coração.",
    74: "Ó Deus, por que nos rejeitaste para sempre? Por que se acende a tua ira contra as ovelhas do teu pasto?",
    75: "A ti, ó Deus, glorificamos, a ti damos louvor, pois o teu nome está perto, as tuas maravilhas o declaram.",
    76: "Conhecido é Deus em Judá; grande é o seu nome em Israel.",
    77: "Clamei a Deus com a minha voz, a Deus levantei a minha voz, e ele inclinou para mim os ouvidos.",
    78: "Escutai a minha lei, povo meu; inclinai os vossos ouvidos às palavras da minha boca.",
    79: "Ó Deus, os gentios vieram à tua herança; contaminaram o teu santo templo; reduziram Jerusalém a montões de pedras.",
    80: "Tu, que és pastor de Israel, dá ouvidos; tu, que guias a José como a um rebanho; tu, que te assentas entre os querubins, resplandece.",
    81: "Exultai a Deus, nossa fortaleza; jubilai ao Deus de Jacó.",
    82: "Deus está na congregação dos poderosos; julga no meio dos deuses.",
    83: "Ó Deus, não estejas em silêncio; não te cales, nem te aquietes, ó Deus,",
    84: "Quão amáveis são os teus tabernáculos, SENHOR dos Exércitos!",
    85: "Abençoaste, SENHOR, a tua terra; fizeste voltar o cativeiro de Jacó.",
    86: "Inclina, SENHOR, os teus ouvidos, e ouve-me, porque estou necessitado e aflito.",
    87: "O seu fundamento está nos montes santos.",
    88: "SENHOR Deus da minha salvação, diante de ti tenho clamado de dia e de noite.",
    89: "As benignidades do SENHOR cantarei perpetuamente; com a minha boca manifestarei a tua fidelidade de geração em geração.",
    90: "SENHOR, tu tens sido o nosso refúgio, de geração em geração.",
    91: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.",
    92: "Bom é louvar ao SENHOR, e cantar louvores ao teu nome, ó Altíssimo;",
    93: "O SENHOR reina; está vestido de majestade. O SENHOR se revestiu e cingiu de poder; o mundo também está firmado, e não poderá vacilar.",
    94: "Ó Senhor Deus, a quem a vingança pertence, ó Deus, a quem a vingança pertence, mostra-te resplandecente.",
    95: "Vinde, cantemos ao SENHOR; jubilemos à rocha da nossa salvação.",
    96: "Cantai ao SENHOR um cântico novo, cantai ao SENHOR toda a terra.",
    97: "O SENHOR reina; regozije-se a terra; alegrem-se as muitas ilhas.",
    98: "Cantai ao SENHOR um cântico novo, porque fez maravilhas; a sua destra e o seu braço santo lhe alcançaram a salvação.",
    99: "O SENHOR reina; tremam os povos. Ele está assentado entre os querubins; comova-se a terra.",
    100: "Celebrai com júbilo ao SENHOR, todas as terras.",
    101: "Cantarei a misericórdia e o juízo; a ti, SENHOR, cantarei.",
    103: "Bendize, ó minha alma, ao SENHOR, e tudo o que há em mim bendiga o seu santo nome.",
    104: "Bendize, ó minha alma, ao SENHOR! SENHOR Deus meu, tu és magnificentíssimo; estás vestido de glória e de majestade.",
    105: "Louvai ao SENHOR, e invocai o seu nome; fazei conhecidas as suas obras entre os povos.",
    106: "Louvai ao SENHOR. Louvai ao SENHOR, porque ele é bom, porque a sua misericórdia dura para sempre.",
    107: "Louvai ao SENHOR, porque ele é bom, porque a sua benignidade dura para sempre.",
    108: "Preparado está o meu coração, ó Deus; cantarei e darei louvores até com a minha glória.",
    109: "Ó Deus do meu louvor, não te cales,",
    110: "Disse o SENHOR ao meu Senhor: Assenta-te à minha mão direita, até que ponha os teus inimigos por escabelo dos teus pés.",
    111: "Louvai ao SENHOR. Louvarei ao SENHOR de todo o meu coração, na assembléia dos justos e na congregação.",
    112: "Louvai ao SENHOR. Bem-aventurado o homem que teme ao SENHOR, que em seus mandamentos tem grande prazer.",
    113: "Louvai ao SENHOR. Louvai, servos do SENHOR, louvai o nome do SENHOR.",
    114: "Quando Israel saiu do Egito, e a casa de Jacó de um povo de língua estranha,",
    115: "Não a nós, SENHOR, não a nós, mas ao teu nome dá glória, por amor da tua benignidade e da tua verdade.",
    116: "Amo ao SENHOR, porque ele ouviu a minha voz e a minha súplica.",
    117: "Louvai ao SENHOR todas as nações, louvai-o todos os povos.",
    118: "Louvai ao SENHOR, porque ele é bom, porque a sua benignidade dura para sempre.",
    119: "Bem-aventurados os retos em seus caminhos, que andam na lei do Senhor.",
    120: "Na minha angústia clamei ao SENHOR, e me ouviu.",
    121: "Levantarei os meus olhos para os montes, de onde vem o meu socorro.",
    122: "Alegrei-me quando me disseram: Vamos à casa do Senhor.",
    123: "A ti levanto os meus olhos, ó tu que habitas nos céus.",
    124: "Se não fora o Senhor, que esteve ao nosso lado, ora diga Israel;",
    125: "Os que confiam no SENHOR serão como o monte de Sião, que não se abala, mas permanece para sempre.",
    126: "Quando o SENHOR trouxe do cativeiro os que voltaram a Sião, estávamos como os que sonham.",
    127: "Se o SENHOR não edificar a casa, em vão trabalham os que a edificam; se o SENHOR não guardar a cidade, em vão vigia a sentinela.",
    128: "Bem-aventurado aquele que teme ao SENHOR e anda nos seus caminhos.",
    129: "Muitas vezes me angustiaram desde a minha mocidade, diga agora Israel;",
    130: "Das profundezas a ti clamo, ó SENHOR.",
    131: "SENHOR, o meu coração não se elevou nem os meus olhos se levantaram; não me exercito em grandes matérias, nem em coisas muito elevadas para mim.",
    132: "Lembra-te, SENHOR, de Davi, e de todas as suas aflições.",
    133: "Oh! quão bom e quão suave é que os irmãos vivam em união.",
    134: "Eis aqui, bendizei ao SENHOR todos vós, servos do SENHOR, que assistis na casa do SENHOR todas as noites.",
    135: "Louvai ao SENHOR. Louvai o nome do SENHOR; louvai-o, servos do SENHOR.",
    136: "Louvai ao SENHOR, porque ele é bom; porque a sua benignidade dura para sempre.",
    137: "Junto aos rios da Babilônia, ali nos assentamos e choramos, quando nos lembramos de Sião.",
    138: "Eu te louvarei, de todo o meu coração; na presença dos deuses a ti cantarei louvores.",
    139: "SENHOR, tu me sondaste, e me conheces",
    140: "Livra-me, ó SENHOR, do homem mau; guarda-me do homem violento,",
    141: "SENHOR, a ti clamo, escuta-me; inclina os teus ouvidos à minha voz, quando a ti clamar.",
    142: "Com a minha voz clamei ao SENHOR; com a minha voz supliquei ao SENHOR.",
    143: "Ó Senhor, ouve a minha oração, inclina os ouvidos às minhas súplicas; escuta-me segundo a tua verdade, e segundo a tua justiça.",
    144: "Bendito seja o SENHOR, minha rocha, que ensina as minhas mãos para a peleja e os meus dedos para a guerra;",
    145: "Eu te exaltarei, ó Deus, rei meu, e bendirei o teu nome pelos séculos dos séculos e para sempre.",
    146: "Louvai ao Senhor. Ó minha alma, louva ao Senhor.",
    147: "Louvai ao SENHOR, porque é bom cantar louvores ao nosso Deus, porque é agradável; decoroso é o louvor.",
    148: "Louvai ao SENHOR. Louvai ao SENHOR desde os céus, louvai-o nas alturas.",
    149: "Louvai ao SENHOR. Cantai ao SENHOR um cântico novo, e o seu louvor na congregação dos santos.",
    150: "Louvai ao SENHOR. Louvai a Deus no seu santuário; louvai-o no firmamento do seu poder.",
}
