

message_text_pt = {
    1: "Bem-aventurado o homem que não anda segundo o conselho dos ímpios, nem se detém no caminho dos pecadores, nem se assenta na roda dos escarnecedores",
    2: "Por que se amotinam os gentios, e os povos imaginam coisas vàs?",
    3: "Senhor, como se têm multiplicado os meus adversários! São muitos os que se levantam contra mim.",
    4: "Ouve-me quando eu clamo, ó Deus da minha justiça, na angústia me deste largueza; tem misericórdia de mim e ouve a minha oração.",
    5: "DÁ ouvidos às minhas palavras, ó Senhor, atende à minha meditação.",
    6: "Senhor, não me repreendas na tua ira, nem me castigues no teu furor.",
    7: "Senhor meu Deus, em ti confio; salva-me de todos os que me perseguem, e livra-me;",
    8: "Ó Senhor, Senhor nosso, quão admirável é o teu nome em toda a terra, pois puseste a tua glória sobre os céus!",
    9: "Eu te louvarei, Senhor, com todo o meu coração; contarei todas as tuas maravilhas.",
    10: "Por que estás ao longe, SENHOR? Por que te escondes nos tempos de angústia?",
    11: "No SENHOR confio; como dizeis à minha alma: Fugi para a vossa montanha como pássaro?",
    12: "Salva-nos, SENHOR, porque faltam os homens bons; porque são poucos os fiéis entre os filhos dos homens.",
    13: "Até quando te esquecerás de mim, SENHOR? Para sempre? Até quando esconderás de mim o teu rosto?",
    14: "Disse o néscio no seu coração: Não há Deus. Têm-se corrompido, fazem-se abomináveis em suas obras, não há ninguém que faça o bem.",
    15: "SENHOR, quem habitará no teu tabernáculo? Quem morará no teu santo monte?",
    16: "Guarda-me, ó Deus, porque em ti confio.",
    17: "Ouve, SENHOR, a justiça; atende ao meu clamor; dá ouvidos à minha oração, que não é feita com lábios enganosos.",
    18: "Eu te amarei, ó SENHOR, fortaleza minha.",
    19: "Os céus declaram a glória de Deus e o firmamento anuncia a obra das suas mãos.",
    20: "O SENHOR te ouça no dia da angústia, o nome do Deus de Jacó te proteja.",
    21: "O rei se alegra em tua força, SENHOR; e na tua salvação grandemente se regozija.",
    22: "Deus meu, Deus meu, por que me desamparaste? Por que te alongas do meu auxílio e das palavras do meu bramido?",
    23: "O SENHOR é o meu pastor, nada me faltará.",
    24: "Do SENHOR é a terra e a sua plenitude, o mundo e aqueles que nele habitam.",
    25: "A ti, SENHOR, levanto a minha alma.",
    26: "Julga-me, SENHOR, pois tenho andado em minha sinceridade; tenho confiado também no SENHOR; não vacilarei.",
    27: "O SENHOR é a minha luz e a minha salvação; a quem temerei? O SENHOR é a força da minha vida; de quem me recearei?",
    28: "A ti clamarei, ó Senhor, Rocha minha; não emudeças para comigo; não aconteça, cal ando-te tu para comigo, que eu fique semelhante aos que descem ao abismo.",
    29: "Dai ao SENHOR, ó filhos dos poderosos, dai ao SENHOR glória e força.",
    30: "Exaltar-te-ei, ó SENHOR, porque tu me exaltaste; e não fizeste com que meus inimigos se alegrassem sobre mim.",
    31: "Em ti, SENHOR, confio; nunca me deixes confundido. Livra-me pela tua justiça.",
    32: "Bem-aventurado aquele cuja transgressão é perdoada, e cujo pecado é coberto.",
    33: "Regozijai-vos no SENHOR, vós justos, pois aos retos convém o louvor.",
    34: "Louvarei ao SENHOR em todo o tempo; o seu louvor estará continuamente na minha boca.",
    35: "Pleiteia, SENHOR, com aqueles que pleiteiam comigo; peleja contra os que pelejam contra mim.",
    36: "A transgressão do ímpio diz no íntimo do meu coração: Não há temor de Deus perante os seus olhos.",
    37: "NÃO te indignes por causa dos malfeitores, nem tenhas inveja dos que praticam a iniqüidade.",
    38: "Ó Senhor, não me repreendas na tua ira, nem me castigues no teu furor.",
    39: "Eu disse: Guardarei os meus caminhos para não pecar com a minha língua; guardarei a boca com um freio, enquanto o ímpio estiver diante de mim.",
    40: "Esperei com paciência no SENHOR, e ele se inclinou para mim, e ouviu o meu clamor.",
    41: "Bem-aventurado é aquele que atende ao pobre; o SENHOR o livrará no dia do mal.",
    42: "Assim como o cervo brama pelas correntes das águas, assim suspira a minha alma por ti, ó Deus!",
    43: "Faze-me justiça, ó Deus, e pleiteia a minha causa contra a nação ímpia. Livra-me do homem fraudulento e injusto.",
    44: "Ó Deus, nós ouvimos com os nossos ouvidos, e nossos pais nos têm contado a obra que fizeste em seus dias, nos tempos da antiguidade.",
    45: "O meu coração ferve com palavras boas, falo do que tenho feito no tocante ao Rei. A minha língua é a pena de um destro escritor.",
    46: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.",
    47: "",
    48: "",
    49: "",
    50: "",
    51: "",
    52: "",
    53: "",
    54: "",
    55: "",
    56: "",
    57: "",
    58: "",
    59: "",
    60: "",
    61: "",
    62: "",
    63: "",
    64: "",
    65: "",
    66: "",
    67: "",
    68: "",
    69: "Livra-me, ó Deus, pois as águas entraram até à minha alma.",
    691: "Livra-me, ó Deus, pois as águas entraram até à minha alma.",
    70: "",
    71: "",
    72: "",
    73: "",
    74: "",
    75: "",
    76: "",
    77: "",
    78: "",
    79: "",
    80: "",
    81: "",
    82: "",
    83: "",
    84: "",
    85: "",
    86: "",
    87: "",
    88: "",
    89: "",
    90: "",
    91: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará.",
    92: "",
    93: "",
    94: "",
    95: "",
    96: "",
    97: "",
    98: "",
    99: "",
    100: "",
    101: "",
    103: "",
    104: "",
    105: "",
    106: "",
    107: "",
    108: "",
    109: "",
    110: "",
    111: "",
    112: "",
    113: "",
    114: "",
    115: "",
    116: "",
    117: "",
    118: "",
    119: "",
    120: "",
    121: "",
    122: "",
    123: "",
    124: "",
    125: "",
    126: "",
    127: "",
    128: "",
    129: "",
    130: "",
    131: "",
    132: "",
    133: "",
    134: "",
    135: "",
    136: "",
    137: "",
    138: "",
    139: "",
    140: "",
    141: "",
    142: "",
    143: "",
    144: "",
    145: "",
    146: "",
    147: "",
    148: "",
    149: "",
    150: "",
}
